---
title: "Word predictor"
author: "A. Rodríguez"
date: "31/1/2021"
output: html_document
---

Set the working directory to the N-grams files in order to save same typing.

```{r load N-grams}
setwd("C:/Users/user/Documents/Capstone Project/N-grams")
load("unigram.Rda")
load("bigram.Rda")
load("trigram.Rda")
load("quadgram.Rda")
```

The next three code chunks address the prediction of bi, tri and quadgrams.

```{r bigram function}
bigram <- function(twog){
    two <- paste(twog,collapse = ' ')
    twosum <- data.frame(bigram="test",frequency=0)
    l <- u_list[unigram==two]
    m <- as.numeric(l$frequency)
    if(length(m)==0) return(NULL)
    
    for(string0 in u_list$unigram){
        text = paste(two,string0)
        found <- b_list[bigram==text]
        n<- as.numeric(found$frequency)
        
        if(length(n)!=0){
            twosum <- rbind(twosum,found)
        }
    }
    
    if(nrow(twosum)==1) return(NULL)
    twosum <- twosum[order(-frequency)]
    
    sen <- unlist(strsplit(as.String(twosum[1,bigram]),' '))
    return (sen[length(sen)])
}
```



```{r trigram function}
trigram <- function(threeg){
    three <- paste(threeg,collapse = ' ')
    threesum <- data.frame(trigram="test",frequency=0)
    l <- b_list[bigram==three]
    m <- as.numeric(l$frequency)
    if(length(m)==0) return(NULL)
    
    for(string0 in u_list$unigram){
        text = paste(three,string0)
        found <- t_list[trigram==text]
        n<- as.numeric(found$frequency)
        
        if(length(n)!=0){
            threesum <- rbind(threesum,found)
        }
    }
    if(nrow(threesum)==1) return(NULL)
    threesum <- threesum[order(-frequency)]
    sen <- unlist(strsplit(as.String(threesum[1,trigram]),' '))
    return (sen[length(sen)])
}
```



```{r quadgram function}
quadgram <- function(fourg){
    four <- paste(fourg,collapse = ' ')
    foursum <- data.frame(quadgram="test",frequency=0)
    l <- t_list[trigram==four]
    m <- as.numeric(l$frequency)
    if(length(m)==0) return(NULL)
    
    for(string0 in unigramlist$unigram){
        text = paste(four,string0)
        found <- q_list[quadgram==text]
        n<- as.numeric(found$frequency)
        
        if(length(n)!=0){
            foursum <- rbind(foursum,found)
            
        }
    }
    if(nrow(foursum)==1) return(NULL)
    foursum <- foursum[order(-frequency)]
    sen <- unlist(strsplit(as.String(foursum[1,fourgram]),' '))
    return (sen[length(sen)])
}
```


Already done the n-gram loops, we then build the next word function, which takes into account the these n-gram functions as a whole.

```{r next word function}
wordpred <- function(sentence){
    value = "click submit button"
    sen = unlist(strsplit(sentence,' '))
    if(length(sen)>=3){value = quadgram(sen[(length(sen)-2):length(sen)])
    }
    if(is.null(value)||length(sen)==2){
        value = trigram(sen[(length(sen)-1):length(sen)])
    }
    if(is.null(value)||length(sen)==1){value = bigram(sen[length(sen)])
    }
    if(is.null(value)){value = "the"} #default value
    
    return(value)
}
```



